services:
  redis:
    image: redis

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password

  vote:
    image: vote-app
    ports:
      - 5001:80

  worker:
    image: worker-app

  result:
    image: result-app
    ports:
      - 5002:80
