version: '3'
services:
  redis:
    image: redis

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password

  vote:
    image: vote-app
    ports:
      - 5001:80
    links:
      - redis

  worker:
    image: worker-app
    links:
      - db
      - redis

  result:
    image: result-app
    ports:
      - 5002:80
    links:
      - db