# simple deployment file 
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
  name: test
spec:
  replicas: 10
  selector: # here it says which deployment is managing
    matchLabels: # this he adds
      app: test
  template: # template for the pods
    metadata: # manifestation of pod, the same as before
      labels:
        app: test # to the pod
    spec:
      containers:
        - image: httpd:alpine3.18
          name: httpd
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1 # max unav during process
      maxSurge: 1 # max up for example here 11
